ASP.NET CORE MVC/ASP.NET.Demo/ASP.NET.Demo/Models/Course.cs
namespace ASP.NET.Demo.Models
{
    using System;
    using System.Collections.Generic;

    public class Course
    {
        public string Name { get; set; }

        public int Id { get; set; }

        public DateTime StartDate { get; set; }

        public DateTime EndDate { get; set; }

        public int PassCredits { get; set; }

        public int HomeTasksCount { get; set; }

        public List<HomeTask> HomeTasks { get; set; }

        public List<Lecturer> Lecturers { get; set; }

        public List<Student> Students { get; set; }
    }
}

ASP.NET CORE MVC/ASP.NET.Demo/ASP.NET.Demo/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;

namespace ASP.NET.Demo.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Net;

    using ASP.NET.Demo.ViewModels;

    using Microsoft.AspNetCore.Authorization;

    using Models.Models;
    using Services;

    public class CourseController : Controller
    {
        private readonly CourseService courseService;
        private readonly StudentService studentService;
        private readonly LecturerService lecturerService;

        public CourseController(CourseService courseService, StudentService studentService, LecturerService lecturerService)
        {
            this.courseService = courseService;
            this.studentService = studentService;
            this.lecturerService = lecturerService;
        }

        // GET
        public IActionResult Courses()
        {
            return View(this.courseService.GetAllCourses());
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            this.courseService.DeleteCourse(id);

            return RedirectToAction("Courses");
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["action"] = nameof(this.Create);
            return this.View("Edit", new Course());
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int id)
        {
            Course course = this.courseService.GetCourse(id);
            if (course == null)
            {
                return this.NotFound();
            }

            ViewData["action"] = nameof(this.Edit);

            return this.View(course);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(Course courseParameter)
        {
            if (courseParameter == null)
            {
                return this.BadRequest();
            }
            courseService.UpdateCourse(courseParameter);
            return this.RedirectToAction(nameof(Courses));
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Create(Course courseParameter)
        {
            if (courseParameter == null)
            {
                return this.BadRequest();
            }

            if (!ModelState.IsValid)
            {
                ViewData["action"] = nameof(this.Create);

                return this.View("Edit", courseParameter);
            }
            this.courseService.CreateCourse(courseParameter);
            return this.RedirectToAction(nameof(Courses));
        }

        [Authorize(Roles = "Admin,Lecturer")]
        [HttpGet]
        public IActionResult AssignStudents(int id)
        {
            var allStudents = this.studentService.GetAllStudents();
            var course = this.courseService.GetCourse(id);
            CourseStudentAssignmentViewModel model = new CourseStudentAssignmentViewModel();

            model.Id = id;
            model.EndDate = course.EndDate;
            model.Name = course.Name;
            model.StartDate = course.StartDate;
            model.PassCredits = course.PassCredits;
            model.Students = new List<StudentViewModel>();

            foreach (var student in allStudents)
            {
                bool isAssigned = course.Students.Any(p => p.StudentId == student.Id);
                model.Students.Add(new StudentViewModel() { StudentId = student.Id, StudentFullName = student.Name, IsAssigned = isAssigned });
            }

            return this.View(model);
        }

        [Authorize(Roles = "Admin,Lecturer")]
        [HttpPost]
        public IActionResult AssignStudents(CourseStudentAssignmentViewModel assignmentViewModel)
        {
            this.courseService.SetStudentsToCourse(assignmentViewModel.Id, assignmentViewModel.Students.Where(p => p.IsAssigned).Select(student => student.StudentId));

            return RedirectToAction("Courses");
        }

        [HttpGet]
        [Authorize(Roles = "Admin,Lecturer")]
        public IActionResult AssignLecturers(int id)
        {
            var allLecturers = this.lecturerService.GetAllLecturers();
            var course = this.courseService.GetCourse(id);
            CourseLecturerAssignmentViewModel model = new CourseLecturerAssignmentViewModel();

            model.Id = id;
            model.EndDate = course.EndDate;
            model.Name = course.Name;
            model.StartDate = course.StartDate;
            model.PassCredits = course.PassCredits;
            model.Lecturers = new List<LecturersViewModel>();

            foreach (var lecturer in allLecturers)
            {
                bool isAssigned = course.Lecturers.Any(p => p.LecturerId == lecturer.Id);
                model.Lecturers.Add(new LecturersViewModel() { LecturerId = lecturer.Id, Name = lecturer.Name, IsAssigned = isAssigned });
            }

            return this.View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin,Lecturer")]
        public IActionResult AssignLecturers(CourseLecturerAssignmentViewModel model)
        {
            this.courseService.SetLecturersToCourse(model.Id, model.Lecturers.Where(p => p.IsAssigned).Select(lecturer => lecturer.LecturerId));

            return RedirectToAction("Courses");
        }
    }
}

ASP.NET CORE MVC/ASP.NET.Demo/ASP.NET.Demo/Controllers/HomeTaskController.cs
using Microsoft.AspNetCore.Mvc;

namespace ASP.NET.Demo.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using ASP.NET.Demo.ViewModels;

    using DataAccess.ADO;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Routing;

    using Models.Models;
    using Services;

    public class HomeTaskController : Controller
    {
        private readonly HomeTaskService homeTaskService;
        private readonly StudentService studentService;

        public HomeTaskController(HomeTaskService homeTaskService, StudentService studentService)
        {
            this.homeTaskService = homeTaskService;
            this.studentService = studentService;
        }

        [HttpGet]
        [Authorize(Roles = "Admin,Lecturer")]
        public IActionResult Create(int courseId)
        {
            ViewData["Action"] = "Create";
            ViewData["CourseId"] = courseId;
            var model = new HomeTask();
            return View("Edit", model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin,Lecturer")]
        public IActionResult Create(HomeTask homeTask, int courseId)
        {
            if (!ModelState.IsValid)
            {
                ViewData["Action"] = "Create";
                ViewData["CourseId"] = courseId;
                return View("Edit", homeTask);
            }
            var routeValueDictionary = new RouteValueDictionary();
            routeValueDictionary.Add("id", courseId);

            this.homeTaskService.CreateHomeTask(homeTask, courseId);
            return RedirectToAction("Edit", "Course", routeValueDictionary);
        }

        [HttpGet]
        [Authorize(Roles = "Admin,Lecturer")]
        public IActionResult Edit(int id)
        {
            HomeTask homeTask = this.homeTaskService.GetHomeTaskById(id);
            if (homeTask == null)
                return this.NotFound();
            ViewData["Action"] = "Edit";

            return View(homeTask);
        }

        [HttpPost]
        [Authorize(Roles = "Admin,Lecturer")]
        public IActionResult Edit(HomeTask homeTaskParameter)
        {
            if (!ModelState.IsValid)
            {
                ViewData["Action"] = "Edit";

                return View(homeTaskParameter);
            }

            var homeTask = this.homeTaskService.GetHomeTaskById(homeTaskParameter.Id);

            var routeValueDictionary = new RouteValueDictionary();
            this.homeTaskService.UpdateHomeTask(homeTaskParameter);
            routeValueDictionary.Add("id", homeTask.Course.Id);
            return RedirectToAction("Edit", "Course", routeValueDictionary);
        }

        [HttpGet]
        [Authorize(Roles = "Admin,Lecturer")]
        public IActionResult Delete(int homeTaskId, int courseId)
        {
            this.homeTaskService.DeleteHomeTask(homeTaskId);

            var routeValueDictionary = new RouteValueDictionary();
            routeValueDictionary.Add("id", courseId);
            return RedirectToAction("Edit", "Course", routeValueDictionary);
        }

        [HttpGet]
        [Authorize(Roles = "Admin,Lecturer")]
        public IActionResult Evaluate(int id)
        {
            var homeTask = this.homeTaskService.GetHomeTaskById(id);

            if (homeTask == null)
            {
                return this.NotFound();
            }

            HomeTaskAssessmentViewModel assessmentViewModel =
                new HomeTaskAssessmentViewModel
                {
                    Date = homeTask.Date,
                    Description = homeTask.Description,
                    Title = homeTask.Title,
                    HomeTaskStudents = new List<HomeTaskStudentViewModel>(),
                    HomeTaskId = homeTask.Id
                };

            if (homeTask.HomeTaskAssessments.Any())
            {
                foreach (var homeTaskHomeTaskAssessment in homeTask.HomeTaskAssessments)
                {
                    assessmentViewModel.HomeTaskStudents.Add(new HomeTaskStudentViewModel()
                    {

                        StudentFullName = homeTaskHomeTaskAssessment.Student.Name,
                        StudentId = homeTaskHomeTaskAssessment.Student.Id,
                        IsComplete = homeTaskHomeTaskAssessment.IsComplete,
                        HomeTaskAssessmentId = homeTaskHomeTaskAssessment.Id
                    });
                }

            }
            else
            {
                foreach (var student in homeTask.Course.Students)
                {
                    assessmentViewModel.HomeTaskStudents.Add(new HomeTaskStudentViewModel() { StudentFullName = student.Student.Name, StudentId = student.StudentId });
                }
            }

            return this.View(assessmentViewModel);
        }

        [Authorize(Roles = "Admin,Lecturer")]
        public IActionResult SaveEvaluation(HomeTaskAssessmentViewModel model)
        {
            var homeTask = this.homeTaskService.GetHomeTaskById(model.HomeTaskId);

            if (homeTask == null)
            {
                return this.NotFound();
            }

            foreach (var homeTaskStudent in model.HomeTaskStudents)
            {
                var target = homeTask.HomeTaskAssessments.Find(p => p.Id == homeTaskStudent.HomeTaskAssessmentId);
                if (target != null)
                {
                    target.Date = DateTime.Now;
                    target.IsComplete = homeTaskStudent.IsComplete;
                }
                else
                {
                    var student = this.studentService.GetStudentById(homeTaskStudent.StudentId);
                    homeTask.HomeTaskAssessments.Add(new HomeTaskAssessment
                    {
                        HomeTask = homeTask,
                        IsComplete = homeTaskStudent.IsComplete,
                        Student = student,
                        Date = DateTime.Now

                    });
                }
                this.homeTaskService.UpdateHomeTask(homeTask);
            }
            return RedirectToAction("Courses", "Course");
        }
    }
}

ASP.NET CORE MVC/ASP.NET.Demo/ASP.NET.Demo/Views/Course/AssignLecturers.cshtml
@model ASP.NET.Demo.ViewModels.CourseLecturerAssignmentViewModel

<form asp-action="AssignLecturers">
    <div class="form-horizontal">
        <h4>Assign</h4>
        <hr />
        @Html.HiddenFor(m => Model.Id)
        <div class="form-group">
            <label class="col-md-5 control-label">@Model.Name</label>
        </div>
        <div class="form-group">
            <label class="col-md-5 control-label">@Model.StartDate</label>
        </div>
        <div class="form-group">
            <label class="col-md-5 control-label">@Model.EndDate</label>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>Lecturer name</th>
                    <th>Assigned</th>
                </tr>
            </thead>
            <tbody>
                @for (var i = 0; i < Model.Lecturers.Count; i++)
                {
                    <tr>
                        <td>@Model.Lecturers[i].Name</td>
                        <td>
                            @Html.CheckBoxFor(m => Model.Lecturers[i].IsAssigned)
                        </td>
                        @Html.HiddenFor(m => Model.Lecturers[i].LecturerId)
                    </tr>
                }
            </tbody>
        </table>


        <div class="form-group">
            <div class="col-md-offset-1 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>

    </div>
</form>

ASP.NET CORE MVC/ASP.NET.Demo/ASP.NET.Demo/Views/Course/AssignStudents.cshtml
@model ASP.NET.Demo.ViewModels.CourseStudentAssignmentViewModel

<form asp-action="AssignStudents">
    <div class="form-horizontal">
        <h4>Assign</h4>
        <hr />
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        @*@Html.Hidden("courseId", ViewData["CourseId"])*@
        @Html.HiddenFor(m => Model.Id)
        <div class="form-group">
            <label class="col-md-5 control-label">@Model.Name</label>
        </div>
        <div class="form-group">
            <label class="col-md-5 control-label">@Model.StartDate</label>
        </div>
        <div class="form-group">
            <label class="col-md-5 control-label">@Model.EndDate</label>
        </div>
        <table class="table">
            <thead>
            <tr>
                <th>Student name</th>
                <th>Assigned</th>
            </tr>
            </thead>
            <tbody>
            @for (var i = 0; i < Model.Students.Count; i++)
            {
                <tr>
                    <td>@Model.Students[i].StudentFullName</td>
                    <td>
                        @Html.CheckBoxFor(m => Model.Students[i].IsAssigned)
                    </td>
                    @Html.HiddenFor(m => Model.Students[i].StudentId)
                </tr>
            }
            </tbody>
        </table>


        <div class="form-group">
            <div class="col-md-offset-1 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>

    </div>
</form>

ASP.NET CORE MVC/ASP.NET.Demo/ASP.NET.Demo/Views/Course/Courses.cshtml
@model IEnumerable<Models.Models.Course>


<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PassCredits)
            </th>
            <th>
                Hometasks count
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PassCredits)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HomeTasks.Count)
                </td>
                <td>
                    @Html.ActionLink("Assign Lecturers", "AssignLecturers", new { id = item.Id }) |
                    @Html.ActionLink("Assign Students", "AssignStudents", new { id = item.Id }) |
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

ASP.NET CORE MVC/ASP.NET.Demo/ASP.NET.Demo/Views/Course/Edit.cshtml
@model Models.Models.Course

<form asp-action="@ViewData["action"]">
    <div class="form-horizontal">
        <h4>Course</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="StartDate" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="EndDate" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PassCredits" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="PassCredits" class="form-control" />
                <span asp-validation-for="PassCredits" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

@if (ViewData["Action"] == "Edit")
{
    <p>
        <a asp-action="Create" asp-controller="HomeTask" asp-route-courseId=@Model.Id>Add New Home Task</a>
    </p>
}
<table class="table">
    <tbody>
        @if (Model.HomeTasks != null)
        {
            foreach (var homeTask in Model.HomeTasks)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => homeTask.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => homeTask.Date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => homeTask.Description)
                    </td>
                    <td>
                        @Html.ActionLink("Evaluate", "Evaluate", "HomeTask", new { id = homeTask.Id }) |
                        @Html.ActionLink("Edit", "Edit", "HomeTask", new { id = homeTask.Id }) |
                        @Html.ActionLink("Delete", "Delete", "HomeTask", new { homeTaskId = homeTask.Id, courseId = Model.Id })
                    </td>
                </tr>
            }
        }
    </tbody>
</table>
<div>
    <a asp-action="Courses">Back to List</a>
</div>