ASP.NET CORE MVC/ASP.NET.Demo/ASP.NET.Demo/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;

namespace ASP.NET.Demo.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Net;

    using ASP.NET.Demo.ViewModels;

    using Microsoft.AspNetCore.Authorization;

    using Models.Models;
    using Services;

    public class CourseController : Controller
    {
        private readonly CourseService courseService;
        private readonly StudentService studentService;
        private readonly LecturerService lecturerService;

        public CourseController(CourseService courseService, StudentService studentService, LecturerService lecturerService)
        {
            this.courseService = courseService;
            this.studentService = studentService;
            this.lecturerService = lecturerService;
        }

        // GET
        public IActionResult Courses()
        {
            return View(this.courseService.GetAllCourses());
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            this.courseService.DeleteCourse(id);

            return RedirectToAction("Courses");
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["action"] = nameof(this.Create);
            return this.View("Edit", new Course());
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int id)
        {
            Course course = this.courseService.GetCourse(id);
            if (course == null)
            {
                return this.NotFound();
            }

            ViewData["action"] = nameof(this.Edit);

            return this.View(course);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(Course courseParameter)
        {
            if (courseParameter == null)
            {
                return this.BadRequest();
            }
            courseService.UpdateCourse(courseParameter);
            return this.RedirectToAction(nameof(Courses));
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Create(Course courseParameter)
        {
            if (courseParameter == null)
            {
                return this.BadRequest();
            }

            if (!ModelState.IsValid)
            {
                ViewData["action"] = nameof(this.Create);

                return this.View("Edit", courseParameter);
            }
            this.courseService.CreateCourse(courseParameter);
            return this.RedirectToAction(nameof(Courses));
        }

        [Authorize(Roles = "Admin,Lecturer")]
        [HttpGet]
        public IActionResult AssignStudents(int id)
        {
            var allStudents = this.studentService.GetAllStudents();
            var course = this.courseService.GetCourse(id);
            CourseStudentAssignmentViewModel model = new CourseStudentAssignmentViewModel();

            model.Id = id;
            model.EndDate = course.EndDate;
            model.Name = course.Name;
            model.StartDate = course.StartDate;
            model.PassCredits = course.PassCredits;
            model.Students = new List<StudentViewModel>();

            foreach (var student in allStudents)
            {
                bool isAssigned = course.Students.Any(p => p.StudentId == student.Id);
                model.Students.Add(new StudentViewModel() { StudentId = student.Id, StudentFullName = student.Name, IsAssigned = isAssigned });
            }

            return this.View(model);
        }

        [Authorize(Roles = "Admin,Lecturer")]
        [HttpPost]
        public IActionResult AssignStudents(CourseStudentAssignmentViewModel assignmentViewModel)
        {
            this.courseService.SetStudentsToCourse(assignmentViewModel.Id, assignmentViewModel.Students.Where(p => p.IsAssigned).Select(student => student.StudentId));

            return RedirectToAction("Courses");
        }

        [HttpGet]
        [Authorize(Roles = "Admin,Lecturer")]
        public IActionResult AssignLecturers(int id)
        {
            var allLecturers = this.lecturerService.GetAllLecturers();
            var course = this.courseService.GetCourse(id);
            CourseLecturerAssignmentViewModel model = new CourseLecturerAssignmentViewModel();

            model.Id = id;
            model.EndDate = course.EndDate;
            model.Name = course.Name;
            model.StartDate = course.StartDate;
            model.PassCredits = course.PassCredits;
            model.Lecturers = new List<LecturersViewModel>();

            foreach (var lecturer in allLecturers)
            {
                bool isAssigned = course.Lecturers.Any(p => p.LecturerId == lecturer.Id);
                model.Lecturers.Add(new LecturersViewModel() { LecturerId = lecturer.Id, Name = lecturer.Name, IsAssigned = isAssigned });
            }

            return this.View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin,Lecturer")]
        public IActionResult AssignLecturers(CourseLecturerAssignmentViewModel model)
        {
            this.courseService.SetLecturersToCourse(model.Id, model.Lecturers.Where(p => p.IsAssigned).Select(lecturer => lecturer.LecturerId));

            return RedirectToAction("Courses");
        }
    }
}

ASP.NET CORE MVC/ASP.NET.Demo/ASP.NET.Demo/Controllers/LecturerController.cs
namespace ASP.NET.Demo.Controllers
{
    using DataAccess.ADO;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using Models.Models;
    using Services;

    public class LecturerController : Controller
    {
        private readonly LecturerService lecturerService;

        public LecturerController(LecturerService lecturerService)
        {
            this.lecturerService = lecturerService;
        }

        // GET
        public IActionResult Lecturers()
        {
            return View(lecturerService.GetAllLecturers());
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int id)
        {
            Lecturer lecturer = lecturerService.GetLecturerById(id);
            ViewData["Action"] = "Edit";
            return this.View(lecturer);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(Lecturer model)
        {
            if (!ModelState.IsValid)
            {
                ViewData["Action"] = "Edit";
                return this.View("Edit", model);
            }
            this.lecturerService.UpdateLecturer(model);

            return RedirectToAction("Lecturers");
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            this.lecturerService.DeleteLecturer(id);
            return RedirectToAction("Lecturers");
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["Action"] = "Create";
            var lecturer = new Lecturer();
            return this.View("Edit", lecturer);
        }


        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult Create(Lecturer model)
        {
            if (!ModelState.IsValid)
            {
                ViewData["Action"] = "Create";
                return this.View("Edit", model);
            }

            this.lecturerService.CreateLecturer(model);
            return RedirectToAction("Lecturers");
        }
    }
}

ASP.NET CORE MVC/ASP.NET.Demo/ASP.NET.Demo/Controllers/SecurityController.cs
namespace ASP.NET.Demo.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using ASP.NET.Demo.ViewModels;

    using Microsoft.AspNetCore.Authentication;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    [Authorize]
    public class SecurityController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;

        private readonly SignInManager<IdentityUser> signInManager;

        private readonly RoleManager<IdentityRole> roleManager;

        public SecurityController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, RoleManager<IdentityRole> roleManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.roleManager = roleManager;
        }

        [TempData]
        public string ErrorMessage { get; set; }

        [HttpGet]
        [AllowAnonymous]
        public async Task<ActionResult> Login(string returnUrl = null)
        {
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginViewModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                await signInManager.SignOutAsync();
                var result = await signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    return RedirectToAction("Courses", "Course");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return View(model);
                }
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("Courses", "Course");
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateUser(CreateUserViewModel createUserViewModel)
        {
            if (ModelState.IsValid)
            {
                var result = await this.userManager.CreateAsync(new IdentityUser(createUserViewModel.Email) { Email = createUserViewModel.Email }, createUserViewModel.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Users");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid create User.");
                    return View(createUserViewModel);
                }
            }

            return View(createUserViewModel);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<ActionResult> CreateUser()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<ActionResult> CreateRole()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateRole(CreateRoleViewModel createRoleViewModel)
        {
            if (ModelState.IsValid)
            {
                var result = await this.roleManager.CreateAsync(new IdentityRole(createRoleViewModel.Role));
                if (result.Succeeded)
                {
                    return RedirectToAction("Courses", "Course");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid create role.");
                    return View(createRoleViewModel);
                }
            }

            return View(createRoleViewModel);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<ActionResult> Users()
        {

            UsersViewModel model = new UsersViewModel() { UserNames = this.userManager.Users.Select(p => p.Email).ToList() };
            return this.View(model);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<ActionResult> AssignUserRole(string userName)
        {
            AssignUserRoleViewModel model = new AssignUserRoleViewModel();
            var user = this.userManager.Users.SingleOrDefault(p => p.Email == userName);
            if (user == null)
            {
                return this.NotFound();
            }

            foreach (var role in this.roleManager.Roles)
            {
                model.UserRoles.Add(new UserRoleViewModel()
                {
                    RoleName = role.Name,
                    IsAssigned = await this.userManager.IsInRoleAsync(user, role.Name)
                });
            }

            return View(model);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<ActionResult> AssignUserRole(AssignUserRoleViewModel model)
        {
            var user = this.userManager.Users.SingleOrDefault(p => p.Email == model.UserName);
            foreach (var userRoleViewModel in model.UserRoles)
            {
                if (await this.userManager.IsInRoleAsync(user, userRoleViewModel.RoleName))
                {
                    await this.userManager.RemoveFromRoleAsync(user, userRoleViewModel.RoleName);
                }

                if (userRoleViewModel.IsAssigned)
                {
                    var result = await this.userManager.AddToRoleAsync(user, userRoleViewModel.RoleName);
                }
            }

            return RedirectToAction("Users");
        }
    }
}

ASP.NET CORE MVC/ASP.NET.Demo/ASP.NET.Demo/Controllers/StudentController.cs
using System.Threading.Tasks;

namespace ASP.NET.Demo.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using Models.Models;
    using Services;

    public class StudentController : Controller
    {
        private readonly StudentService studentService;
        private readonly IAuthorizationService authorizationService;

        public StudentController(StudentService studentService, IAuthorizationService authorizationService)
        {
            this.studentService = studentService;
            this.authorizationService = authorizationService;
        }

        // GET
        public IActionResult Students()
        {
            return View(studentService.GetAllStudents());
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var student = studentService.GetStudentById(id);
            var result = await authorizationService.AuthorizeAsync(User, student, "SameUserPolicy");
            if (result.Succeeded)
            {
                ViewData["Action"] = "Edit";
                return this.View(student);
            }

            return Unauthorized();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Student model)
        {
            if (!ModelState.IsValid)
            {
                ViewData["Action"] = "Edit";
                return this.View("Edit", model);
            }

            var result = await authorizationService.AuthorizeAsync(User, model, "SameUserPolicy");
            if (result.Succeeded)
            {
                this.studentService.UpdateStudent(model);

                return RedirectToAction("Students");
            }
            return Unauthorized();
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            this.studentService.DeleteStudent(id);
            return RedirectToAction("Students");
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Create()
        {
            ViewData["Action"] = "Create";
            var student = new Student();
            return this.View("Edit", student);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult Create(Student model)
        {
            if (!ModelState.IsValid)
            {
                ViewData["Action"] = "Create";
                return this.View("Edit", model);
            }

            this.studentService.CreateStudent(model);
            return RedirectToAction("Students");

        }
    }
}

ASP.NET CORE MVC/ASP.NET.Demo/ASP.NET.Demo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP.NET.Demo</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ASP.NET.Demo</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li><a asp-controller="Course" asp-action="Courses">Courses</a></li>
                    <li><a asp-controller="Student" asp-action="Students">Students</a></li>
                    <li><a asp-controller="Lecturer" asp-action="Lecturers">Lecturers</a></li>
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li><a asp-controller="Security" asp-action="Login">Login</a></li>
                    }
                    else
                    {

                        <li><a asp-controller="Security" asp-action="Logout">Logout</a></li>
                        if (User.IsInRole("Admin"))
                        {
                            <li><a asp-controller="Security" asp-action="CreateUser">CreateUser</a></li>
                            <li><a asp-controller="Security" asp-action="Users">AssignUserRole</a></li>
                            <li><a asp-controller="Security" asp-action="CreateRole">CreateRole</a></li>
                        }
                        <li><p>Hello, @User.Identity.Name</p></li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - ASP.NET.Demo</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>